package org.opendevstack.apiservice.project.exception;

public enum ErrorKey {

    OK("000", ErrorMessage.SUCCESS),
    PRODUCT_NOT_FOUND("001", ErrorMessage.NOT_FOUND),
    ACCESS_DENIED("002", ErrorMessage.FORBIDDEN),
    INTERNAL_ERROR("003", ErrorMessage.INTERNAL_ERROR),
    INVALID_AUTH_HEADER("004", ErrorMessage.BAD_REQUEST),
    MISSING_AUTH_HEADER("005", ErrorMessage.BAD_REQUEST),
    INVALID_PARAMETERS("006", ErrorMessage.BAD_REQUEST),
    X2_ACCOUNT_MISSING_GROUPS("007", ErrorMessage.NOT_FOUND),
    ONLY_INVITED_PROJECT("008", ErrorMessage.FORBIDDEN),
    ONCE_PER_PROJECT("009", ErrorMessage.FORBIDDEN),
    COMPONENT_PARAM_NOT_MEET_REGEX("010", ErrorMessage.BAD_REQUEST),
    INVALID_LOCATION("011", ErrorMessage.INVALID_LOCATION),
    PROJECT_NOT_FOUND("012", ErrorMessage.NOT_FOUND),
    COMPONENT_NOT_FOUND("013", ErrorMessage.NOT_FOUND),
    BAD_REQUEST_BODY("014", ErrorMessage.BAD_REQUEST),
    FORBIDDEN("015", ErrorMessage.FORBIDDEN),
    DUPLICATE_RECORD("016", ErrorMessage.RECORD_ALREADY_EXISTS),
    COMPONENT_PARAM_INVALID_FORMAT("017", ErrorMessage.BAD_REQUEST),
    PROJECT_KEY_INVALID_FORMAT("018", ErrorMessage.PROJECT_KEY_NOT_MET_THE_PATTERN),
    PROJECT_NAME_INVALID_FORMAT("019", ErrorMessage.PROJECT_NAME_NOT_MET_THE_PATTERN),
    PROJECT_DESCRIPTION_INVALID_FORMAT("020", ErrorMessage.PROJECT_DESCRIPTION_NOT_MET_THE_PATTERN),
    PROJECT_OWNER_INVALID_FORMAT("021", ErrorMessage.PROJECT_OWNER_NOT_MET_THE_PATTERN),
    PROJECT_X2ACCOUNT_INVALID_FORMAT("022", ErrorMessage.PROJECT_X_2_ACCOUNT_NOT_MET_THE_PATTERN),
    BAD_REQUEST_FLAVOR_CONFIG_ITEM("023", ErrorMessage.PROJECT_FLAVOUR_AND_CONFIG_ITEM_CANNOT_BE_BOTH_NULL),
    MANDATORY_OWNER("024", ErrorMessage.OWNER_MUST_BE_PRESENT_IF_THE_X_2_ACCOUNT_IS_PRESENT),
    PROJECT_ALREADY_EXISTS("025", ErrorMessage.PROJECT_ALREADY_EXISTS),
    PROJECT_SAME_PROJECT_NAME_ALREADY_EXISTS("026", ErrorMessage.PROJECT_WITH_SAME_PROJECT_NAME_ALREADY_EXISTS),
    CLIENT_APP_NOT_REGISTERED("027", ErrorMessage.CLIENT_APP_NOT_REGISTERED_MANUAL_REGISTRATION_REQUIRED),
    INVALID_PROJECT_FLAVOR("028", ErrorMessage.BAD_REQUEST),
    INVALID_CONFIG_ITEM("029", ErrorMessage.BAD_REQUEST);

    private String key;
    private String message;

    ErrorKey(String key, String message) {
        this.key = key;
        this.message = message;
    }

    public String getKey() {
        return this.key;
    }

    public String getMessage() {
        return this.message;
    }
}
