openapi: 3.0.3
info:
  title: ODS API Server
  description: API documentation for ODS (Open DevStack) API Service
  contact:
    name: ODS Team
  version: v0.0.1
servers:
  - url: http://{baseurl}/api/pub/v0
    variables:
      baseurl:
        default: localhost:8080
        description: Development environment
tags:
- name: Projects Internal
  description: API for manage EDP projects with extended methods
paths:
  /projects/{projectKey}:
    patch:
      tags:
        - Projects Internal
      summary: Updates projects by project key.
      description: Updates the current status and details of the project identified by the given project key.
      operationId: updateProject
      parameters:
        - name: projectKey
          in: path
          required: true
          schema:
            type: string
          description: Project key to retrieve information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        '204':
          description: Project information updated successfully.
        '404':
          description: Project not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjectResponse'
        "401":
          description: Invalid client token on the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrorMessage'
        "403":
          description: Insufficient permissions for the client to access the resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrorMessage'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjectResponse'
components:
  schemas:
    RestErrorMessage:
      properties:
        message:
          type: string
      required:
        - message
    UpdateProjectRequest:
      type: object
      properties:
        status:
          type: string
          description: Status of the project. If not in the allowed list, error INVALID_STATUS (030) is returned.
      additionalProperties: false
    CreateProjectResponse:
      type: object
      properties:
        projectKey:
          type: string
        httStatus:
          type: string
        status:
          type: string
        projectFlavor:
          type: string
        message:
          type: string
        error:
          type: string
        errorKey:
          type: string
        errorDescription:
          type: string
        location:
          type: string