/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.opendevstack.apiservice.project.api;

import org.opendevstack.apiservice.project.model.Component;
import org.opendevstack.apiservice.project.model.CreateComponentRequest;
import org.opendevstack.apiservice.project.model.CreateComponentResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "projectComponents", description = "the projectComponents API")
public interface ProjectComponentsApi {

    public static final String PATH_CREATE_PROJECT_COMPONENT = "/projects/{projectId}/components/";
    /**
     * POST /projects/{projectId}/components/ : Create a component in a project
     * Retrieves information about a specific component
     *
     * @param projectId Project id (required)
     * @param createComponentRequest Component data (optional)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Authentication information is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Endpoint not found / Project not found / Product not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createProjectComponent",
        summary = "Create a component in a project",
        description = "Retrieves information about a specific component",
        tags = { "projectComponents" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateComponentResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request"),
            @ApiResponse(responseCode = "401", description = "Authentication information is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Endpoint not found / Project not found / Product not found"),
            @ApiResponse(responseCode = "500", description = "Internal Server Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProjectComponentsApi.PATH_CREATE_PROJECT_COMPONENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<CreateComponentResponse> createProjectComponent(
        @Parameter(name = "projectId", description = "Project id", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "CreateComponentRequest", description = "Component data") @Valid @RequestBody(required = false) @Nullable CreateComponentRequest createComponentRequest
    );


    public static final String PATH_GET_PROJECT_COMPONENT = "/projects/{projectId}/components/{componentId}";
    /**
     * GET /projects/{projectId}/components/{componentId} : Get component information
     * Retrieves information about a specific component
     *
     * @param projectId Project id (required)
     * @param componentId Component id (required)
     * @return Component information (status code 200)
     */
    @Operation(
        operationId = "getProjectComponent",
        summary = "Get component information",
        description = "Retrieves information about a specific component",
        tags = { "projectComponents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Component information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Component.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectComponentsApi.PATH_GET_PROJECT_COMPONENT,
        produces = { "application/json" }
    )
    
    ResponseEntity<Component> getProjectComponent(
        @Parameter(name = "projectId", description = "Project id", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "componentId", description = "Component id", required = true, in = ParameterIn.PATH) @PathVariable("componentId") String componentId
    );

}
