/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.opendevstack.apiservice.marketplacemetrics.api;

import org.opendevstack.apiservice.marketplacemetrics.model.MarketplaceProjectComponentsMetrics;
import org.opendevstack.apiservice.marketplacemetrics.model.RestErrorMessage;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "MarketplaceMetrics", description = "the MarketplaceMetrics API")
public interface MarketplaceMetricsApi {

    public static final String PATH_GET_MARKETPLACE_PROJECT_COMPONENTS_METRICS = "/metrics/marketplace/project-components";
    /**
     * GET /metrics/marketplace/project-components : Get Marketplace metrics regarding project components.
     * Returns all the components that were provisioned from the Marketplace in all the projects.
     *
     * @param page Page number (from 0 until limit) (optional, default to 0)
     * @param size Page size (optional, default to 20)
     * @return A paginated list of all the provisioned project components (status code 200)
     *         or Invalid client token on the request. (status code 401)
     *         or Insufficient permissions for the client to access the resource. (status code 403)
     *         or Server error. (status code 500)
     */
    @Operation(
        operationId = "getMarketplaceProjectComponentsMetrics",
        summary = "Get Marketplace metrics regarding project components.",
        description = "Returns all the components that were provisioned from the Marketplace in all the projects.",
        tags = { "MarketplaceMetrics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A paginated list of all the provisioned project components", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MarketplaceProjectComponentsMetrics.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid client token on the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "403", description = "Insufficient permissions for the client to access the resource.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server error.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MarketplaceMetricsApi.PATH_GET_MARKETPLACE_PROJECT_COMPONENTS_METRICS,
        produces = { "application/json" }
    )
    
    ResponseEntity<MarketplaceProjectComponentsMetrics> getMarketplaceProjectComponentsMetrics(
        @Parameter(name = "page", description = "Page number (from 0 until limit)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "Page size", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    );

}
